#!/usr/bin/env python3
"""Sync the newest published omnideck desktop-app release into Arbor site data."""

from __future__ import annotations

import datetime as dt
import json
import os
import pathlib
import sys
import urllib.error
import urllib.request


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "desktop_release.toml"
REPOSITORY = os.environ.get("OMNIDECK_DESKTOP_RELEASE_REPO", "omnideck-dev/omnideck")
API_URL = f"https://api.github.com/repos/{REPOSITORY}/releases?per_page=20"


def toml_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{int(value)} B"
        value /= 1024
    raise AssertionError("unreachable")


def fetch_releases() -> list[dict[str, object]]:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "omnideck-site-release-sync",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    request = urllib.request.Request(API_URL, headers=headers)
    with urllib.request.urlopen(request, timeout=20) as response:
        return json.load(response)


def newest_published_release(releases: list[dict[str, object]]) -> dict[str, object]:
    published = [release for release in releases if not release.get("draft") and release.get("published_at")]
    if not published:
        raise RuntimeError(f"{REPOSITORY} has no published releases")
    return max(published, key=lambda release: str(release["published_at"]))


def asset_table(release: dict[str, object]) -> dict[str, dict[str, object]]:
    assets = {str(asset["name"]): asset for asset in release.get("assets", [])}

    def select(*suffixes: str) -> dict[str, object]:
        for suffix in suffixes:
            for name, asset in assets.items():
                if name.endswith(suffix) and not name.endswith(".sha256"):
                    checksum = assets.get(f"{name}.sha256")
                    return {
                        "filename": name,
                        "url": asset["browser_download_url"],
                        "size": human_size(int(asset["size"])),
                        "checksum_url": checksum["browser_download_url"] if checksum else "",
                    }
        return {"filename": "", "url": "", "size": "", "checksum_url": ""}

    return {
        "macos_arm64": select("_aarch64.dmg"),
        "macos_x64": select("_x64.dmg"),
        "windows_x64": select("_x64-setup.exe"),
        "windows_arm64": select("_arm64-setup.exe"),
        "linux_x64_appimage": select("_amd64.AppImage"),
        "linux_arm64_appimage": select("_aarch64.AppImage"),
        "linux_x64_deb": select("_amd64.deb"),
        "linux_arm64_deb": select("_arm64.deb"),
        "linux_x64_rpm": select(".x86_64.rpm"),
        "linux_arm64_rpm": select(".aarch64.rpm"),
    }


def render(release: dict[str, object], downloads: dict[str, dict[str, object]]) -> str:
    tag = str(release["tag_name"])
    version = tag.removeprefix("v")
    published_at = dt.datetime.fromisoformat(str(release["published_at"]).replace("Z", "+00:00"))
    prerelease = bool(release.get("prerelease"))
    lines = [
        "# Generated by scripts/sync-desktop-release.py. Keep this file checked in as the CI fallback.",
        "[release]",
        f"repository = {toml_string(REPOSITORY)}",
        f"tag = {toml_string(tag)}",
        f"version = {toml_string(version)}",
        f"name = {toml_string(release.get('name') or tag)}",
        f"channel = {toml_string('Preview' if prerelease else 'Stable')}",
        f"prerelease = {'true' if prerelease else 'false'}",
        f"published = {toml_string(f'{published_at:%B} {published_at.day}, {published_at:%Y}')}",
        f"published_iso = {toml_string(release['published_at'])}",
        f"url = {toml_string(release['html_url'])}",
        "",
    ]
    for table, asset in downloads.items():
        lines.extend(
            [
                f"[{table}]",
                f"filename = {toml_string(asset['filename'])}",
                f"url = {toml_string(asset['url'])}",
                f"size = {toml_string(asset['size'])}",
                f"checksum_url = {toml_string(asset['checksum_url'])}",
                "",
            ]
        )
    return "\n".join(lines)


def main() -> int:
    try:
        release = newest_published_release(fetch_releases())
        downloads = asset_table(release)
        missing_os = [
            label
            for label, tables in {
                "macOS": ("macos_arm64", "macos_x64"),
                "Windows": ("windows_x64", "windows_arm64"),
                "Linux": (
                    "linux_x64_deb",
                    "linux_arm64_deb",
                    "linux_x64_rpm",
                    "linux_arm64_rpm",
                ),
            }.items()
            if not any(downloads[table]["url"] for table in tables)
        ]
        if missing_os:
            raise RuntimeError(f"release {release['tag_name']} is missing assets for: {', '.join(missing_os)}")
        content = render(release, downloads)
    except (OSError, RuntimeError, KeyError, TypeError, urllib.error.URLError, json.JSONDecodeError) as error:
        if OUTPUT.exists():
            print(f"warning: desktop release sync failed; preserving checked-in data: {error}", file=sys.stderr)
            return 0
        raise

    temporary = OUTPUT.with_suffix(".toml.tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(OUTPUT)
    print(f"Synced Desktop release {release['tag_name']} from {REPOSITORY}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
