#!/usr/bin/env python3
"""Sync the newest published omnideck desktop-app release into Arbor site data."""

from __future__ import annotations

import datetime as dt
import json
import pathlib

from release_data import APP_REPOSITORY, desktop_releases, fetch_releases, write_atomic


ROOT = pathlib.Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "data" / "desktop_release.toml"
REPOSITORY = APP_REPOSITORY


def toml_string(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def human_size(size: int) -> str:
    value = float(size)
    for unit in ("B", "KB", "MB", "GB"):
        if value < 1024 or unit == "GB":
            return f"{value:.1f} {unit}" if unit != "B" else f"{int(value)} B"
        value /= 1024
    raise AssertionError("unreachable")


def newest_published_release(releases: list[dict[str, object]]) -> dict[str, object]:
    published = desktop_releases(releases)
    if not published:
        raise RuntimeError(f"{REPOSITORY} has no published desktop releases")
    return published[0]


def asset_table(release: dict[str, object]) -> dict[str, dict[str, object]]:
    assets = {str(asset["name"]): asset for asset in release.get("assets", [])}

    def select(*suffixes: str) -> dict[str, object]:
        for suffix in suffixes:
            for name, asset in assets.items():
                if name.endswith(suffix) and not name.endswith(".sha256"):
                    checksum = assets.get(f"{name}.sha256")
                    return {
                        "filename": name,
                        "url": asset["browser_download_url"],
                        "size": human_size(int(asset["size"])),
                        "checksum_url": checksum["browser_download_url"] if checksum else "",
                    }
        return {"filename": "", "url": "", "size": "", "checksum_url": ""}

    return {
        "macos_arm64": select("_aarch64.dmg"),
        "macos_x64": select("_x64.dmg"),
        "windows_x64": select("_x64-setup.exe"),
        "windows_arm64": select("_arm64-setup.exe"),
        "linux_x64_appimage": select("_amd64.AppImage"),
        "linux_arm64_appimage": select("_aarch64.AppImage"),
        "linux_x64_deb": select("_amd64.deb"),
        "linux_arm64_deb": select("_arm64.deb"),
        "linux_x64_rpm": select(".x86_64.rpm"),
        "linux_arm64_rpm": select(".aarch64.rpm"),
    }


def render(release: dict[str, object], downloads: dict[str, dict[str, object]]) -> str:
    tag = str(release["tag_name"])
    version = tag.removeprefix("v")
    published_at = dt.datetime.fromisoformat(str(release["published_at"]).replace("Z", "+00:00"))
    prerelease = bool(release.get("prerelease"))
    lines = [
        "# Generated by scripts/sync-desktop-release.py. Do not edit by hand.",
        "[release]",
        f"repository = {toml_string(REPOSITORY)}",
        f"tag = {toml_string(tag)}",
        f"version = {toml_string(version)}",
        f"name = {toml_string(release.get('name') or tag)}",
        f"channel = {toml_string('Preview' if prerelease else 'Stable')}",
        f"prerelease = {'true' if prerelease else 'false'}",
        f"published = {toml_string(f'{published_at:%B} {published_at.day}, {published_at:%Y}')}",
        f"published_iso = {toml_string(release['published_at'])}",
        f"url = {toml_string(release['html_url'])}",
        "",
    ]
    for table, asset in downloads.items():
        lines.extend(
            [
                f"[{table}]",
                f"filename = {toml_string(asset['filename'])}",
                f"url = {toml_string(asset['url'])}",
                f"size = {toml_string(asset['size'])}",
                f"checksum_url = {toml_string(asset['checksum_url'])}",
                "",
            ]
        )
    return "\n".join(lines)


def sync(releases):
    release = newest_published_release(releases)
    downloads = asset_table(release)
    missing = [label for label, asset in downloads.items()
               if not asset["url"] or not asset["checksum_url"]]
    if missing:
        raise RuntimeError(f"desktop release {release['tag_name']} is missing packages or checksums: {', '.join(missing)}")
    write_atomic(OUTPUT, render(release, downloads))
    print(f"Synced Desktop release {release['tag_name']} from {REPOSITORY}")
    return release, downloads


def main() -> int:
    sync(fetch_releases(REPOSITORY))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
