#!/usr/bin/env python3
"""Build the release feed and installer data from one consistent API snapshot."""

import importlib.util
import json
import pathlib
import re

from release_data import (APP_REPOSITORY, CLI_REPOSITORY, fetch_releases,
                          publication_time, published_releases, write_atomic)


ROOT = pathlib.Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("desktop", ROOT / "scripts/sync-desktop-release.py")
desktop = importlib.util.module_from_spec(spec)
spec.loader.exec_module(desktop)


def summary(body):
    # Use published prose only; the full notes remain authoritative.
    paragraphs = re.split(r"\n\s*\n", body or "")
    paragraph = next((part for part in paragraphs if part.strip()
                      and not part.lstrip().startswith(("#", "```", "<!--"))), "")
    paragraph = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", paragraph)
    paragraph = re.sub(r"^[\s*+-]+", "", paragraph)
    paragraph = re.sub(r"[`*_]", "", paragraph)
    if paragraph.startswith("Full Changelog:"):
        return ""
    paragraph = " ".join(paragraph.split())
    return paragraph if len(paragraph) <= 240 else paragraph[:237].rsplit(" ", 1)[0] + "…"


def entry(release, repository, kind):
    tag = release["tag_name"]
    version = tag.removeprefix("app-").removeprefix("v")
    published = publication_time(release)
    return {
        "kind": kind,
        "repository": repository,
        "tag": tag,
        "title": f"{kind} {version}",
        "channel": "Preview" if release.get("prerelease") else "Stable",
        "published_iso": release["published_at"],
        "published": f"{published:%B} {published.day}, {published:%Y}",
        "url": release["html_url"],
        "summary": summary(release.get("body")),
    }


def feed(app_releases, cli_releases):
    entries = []
    for release in published_releases(app_releases):
        tag = release["tag_name"]
        if tag.startswith("app-v"):
            entries.append(entry(release, APP_REPOSITORY, "App / runtime"))
        elif tag.startswith("v"):
            entries.append(entry(release, APP_REPOSITORY, "Desktop installer"))
    entries.extend(entry(release, CLI_REPOSITORY, "CLI")
                   for release in published_releases(cli_releases)
                   if release["tag_name"].startswith("v"))
    entries.sort(key=lambda item: item["published_iso"], reverse=True)
    if not entries:
        raise RuntimeError("No published OmniDeck releases found")
    return entries[:30]


def render(entries):
    lines = ["# Generated by scripts/sync-releases.py. Do not edit by hand."]
    for table, item in [("[latest]", entries[0]), *[("[[items]]", item) for item in entries]]:
        lines.extend(["", table])
        lines.extend(f"{key} = {json.dumps(value, ensure_ascii=False)}" for key, value in item.items())
    return "\n".join(lines) + "\n"


def main():
    app_releases = fetch_releases(APP_REPOSITORY)
    cli_releases = fetch_releases(CLI_REPOSITORY)
    entries = feed(app_releases, cli_releases)
    release, downloads = desktop.sync(app_releases)
    write_atomic(ROOT / "data/releases.toml", render(entries))
    manifest = {
        "releases": entries,
        "desktop_tag": release["tag_name"],
        "desktop_url": release["html_url"],
        "downloads": downloads,
    }
    write_atomic(ROOT / "static/releases.json", json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")
    print(f"Synced {len(entries)} releases; latest ship: {entries[0]['title']}")


if __name__ == "__main__":
    main()
